server.port=8083
server.error.include-message=always
server.error.include-binding-errors=always

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

### CONFIGURACAO INICIALIZACAO ###
#spring.sql.init.mode=always
#spring.datasource.initialization-mode=always

### CONFIGURAÇÃO DATASOURCE ###
spring.datasource.url=jdbc:postgresql://localhost:5432/simobapi?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.hibernate.ddl-auto=update

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true


### CONFIGURAÇÃO FLYWAY ###
spring.flyway.url=jdbc:postgresql://localhost:5432/simobapi
spring.flyway.user=postgres
spring.flyway.password=1234
spring.flyway.locations=filesystem:src/main/resources/db/migration
#spring.flyway.mixed=true
#spring.flyway.cleanDisabled=true
#spring.flyway.schemas=public
#spring.flyway.enabled=true
#spring.flyway.baselineOnMigrate=true


### CONFIGURACAO DEVTOOLS ###
spring.devtools.restart.enabled=false


### CONFIGURACAO TOKEN ###
simob.app.jwt.secret= A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*\yL5S8EJN:%P:X%H9>#nYLrX}@\s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4\Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
simob.app.jwt.expiration= 7200

